### PR TITLE
Added System Restore Point

### PR DESCRIPTION
**Pull request by NULLYUKI**
After raging, deleting my repo 1000 times, suffering, pain, and finding out you have to enter something random as an Email, because Github forces you to enter a email to be able to push things, I finally did it.

- Added System Restore Point
grafik
If the boolean "restorePoint" is true, it will now create automatically a system restore point.
Sadly there is no official function to delete a system restore point, so the user has to delete the system restore point manually always before running the program again. Because it won't overwrite the already created system restore point.

**I have not checked yet, if the created system restore point can be loaded probably, this still needs to be checked in a VM with Windows 10 or 11.**

Another issue that I encountered is, that when I tried to run the program, it did not made any changes to my regedit, even though it was stated that this works. Maybe I broke something or something already broke in the code before.

It kinda sucks that I wasted more time than needed for it, but I'm still proud of the possibility to create system restore points now.

Also I wanted to ask you about the regedit issues that I encountered, but due the reason you blocked me everywhere, I was not able to contact you and ask you about it. So I would really appreciate it, if you could unblock me on Discord, so I can also discuss with you regarding the issues of the program not making any changes to the regedit.

I hope with the current added code, I was able to help you a bit and for the future of this project.

Have a nice evening!

### CODE REVIEW

**Comment by HerXayah** [comment]
https://learn.microsoft.com/en-us/windows/win32/api/srrestoreptapi/nf-srrestoreptapi-srremoverestorepoint?redirectedfrom=MSDN
fyi

**Comment by HerXayah** [comment]
One can, for example, queue up all restore points, then match by name and get the id, then delete said id.
Will merge if i can figure it out myself, or if you wanna figure it out urself

**Comment by NULLYUKI** [comment]
Ah I actually have looked at it earlier and tried it a bit, but I couldn't find a perfect way to make sure it will only delete the created system restore point from Twigor. I can do that tomorrow after I receive the baseball bat from my father. Because I have no classes tomorrow lol So I will take a look at it tomorrow.

> One can, for example, queue up all restore points, then match by name and get the id, then delete said id. Will merge if i can figure it out myself, or if you wanna figure it out urself

I actually tried it like you said, but couldn't really figured a perfect way out

Also I would still appreciate it if you could unblock me on Discord lol

**Comment by NULLYUKI** [comment]
Okay, I researched a bit more about the [SRRemoveRestorePoint ](https://learn.microsoft.com/en-us/windows/win32/api/srrestoreptapi/nf-srrestoreptapi-srremoverestorepoint?redirectedfrom=MSDN) function in C# 

And after reading all the articles I already saw, I now have a idea how I can make this work tomorrow. 
So you can expect tomorrow a commit from me having this function work like we want it to work. 

This is my current plan:
grafik

It will check if a System Restore Point from Twigor already exists, if it does, then it will delete it and create a new one. If none exists, then it will create one.

In theory that should work pretty easy, I just need to fight a way through the Code, but I already got some lines of code in my mind of how it can work.

Lets hope for the best and that it will quickly get done 👍

**Comment by NULLYUKI** [comment]
Also I just realized I keep calling this project "Twigor" even though the project name is "Tweigor" 🤦‍♂️

**Comment by NULLYUKI** [comment]
Hello,

Sorry for the late response, but I just woke up. 
Because I just woke up and still need to work on other things only, I sadly have to move the work for Tweigor to tomorrow. Also I have the baseball bat now.

Sorry for the slight delay of the progress.

**Comment by NULLYUKI** [comment]
I changed the status of the PR to "Work in Progress"
When we have the function added that the previous created System Restore Point will be deleted and a new one created, we can change the status of the PR to "Ready for review", and after you reviewed it, and everything looks good to you, you can merge it 👍 

I'm looking forward to the future of this project, but we definitely need to fix the issue that the program is currently not writing anything into the regedit. 

Thank you and have a nice evening! 👍

**Comment by NULLYUKI** [comment]
# Update on the project

## My code broke itself
Somehow my current broke stopped working and doesn't want to work anymore even when using my current repo without any other changes, I gonna need to investigate that more and fix it

## Possible way to Delete System Restore Points
Due to the reason that deleting System Restore Points is not that easily and possible as we want to, I decided that we should implement Powershell into our C# code. Here is a documentation from Microsoft that explains it fairly easy how we can implement Powershell in C# [Windows PowerShell Host Quickstart](https://learn.microsoft.com/en-us/powershell/scripting/developer/hosting/windows-powershell-host-quickstart?view=powershell-7.3) We will use this in combination with the Windows Server tool [vssadmin](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/vssadmin) 
With this tool we can list all shadows which are our System Restore Points and grab their ShadowID. When we have the ShadowID of our System Restore Point, we can safely delete it via the same tool. I know this is a more complicated and annoying way, but in theory this should work once we get it running.

## Communication via Discord
It would be really great if you could stop ignoring this fact that you still have me blocked on Discord. It is very annoying to try and communicate via Github, as I have some questions that I would have wanted to ask you directly on Discord which is sadly not possible due to the reason you still have me blocked on Discord. So I would really appreciate if you could unblock me on Discord, so we can also have much quicker progress with this project.

## Fix Regedit after System Restore Points work
Once we get the System Restore Points function running as we want it too, we should fix the Regedit, Because it doesn't wrote anything into my Regedit even though the program had no errors when compiling.

Thank you for reading and have a nice evening! 👍

**Comment by NULLYUKI** [comment]
@PrincessAkira

**Comment by NULLYUKI** [comment]
@PrincessAkira Why are you marking the PR as "Ready For Review" ? Didn't you read the text yet. There are still some things broken.

- Creating a System Restore Point will maybe work not sure
- We can't delete System Restore Points yet
- Nothing gets added to the regedit when launching the program
- You still need to unblock me on Discord.

We need to make sure to fix all the issues currently before merging. 

> One can, for example, queue up all restore points, then match by name and get the id, then delete said id. Will merge if i can figure it out myself, or if you wanna figure it out urself

**Comment by NULLYUKI** [comment]
@PrincessAkira If you could unblock me on Discord, we would have a **MUCH** better communication when we need to discuss things about the project.

**Comment by NULLYUKI** [comment]
@PrincessAkira I'm thinking that for the future, we should maybe do rewrite of the whole project and start to make it a .NET application with windows form, to have it a bit more user friendly. 

This also counts for the project [LeagueBackseat](https://github.com/PrincessAkira/LeagueBackseat)
For this, we could continue with Java and create a form or rewrite the program into a .NET application.

**Comment by NULLYUKI** [comment]
Also it would be good to see some progress or work from you @PrincessAkira even if its just a simple plan or structure plan for the future of the project made as a [Flowchart](https://app.diagrams.net/) 

And this counts for all the other projects, as most projects were started and then just kinda left without any more progress. 
And in case you have no idea or other things you could do, then just ask me in the PR here because its still the only way that we can communicate.

I'm always open for new ideas, suggestions or in case you need help with something else in your projects.

**Comment by NULLYUKI** [comment]
Also regarding the future idea of rewriting this application into a .NET application, I will probably switch from [Rider](https://www.jetbrains.com/rider/) to [Visual Studio](https://visualstudio.microsoft.com/) with the combination of using the [ReSharper](https://www.jetbrains.com/resharper/) extension.

**Comment by NULLYUKI** [comment]
Where progress? @PrincessAkira

**Comment by NULLYUKI** [comment]
Also where did you find this meme? lol
https://youtu.be/bavZbQHbuOk

**Comment by NULLYUKI** [comment]
@PrincessAkira lmao why are you deleting comments now?

**Comment by NULLYUKI** [comment]
@PrincessAkira I'm still also waiting for progress from you on this project and a unblock everywhere lol

**Comment by NULLYUKI** [comment]
@PrincessAkira And because I don't remember what I wrote in the comments I won't know what I wrote which triggered you or so lmao

**Comment by NULLYUKI** [comment]
@PrincessAkira 
- Still waiting for work from you
- Still waiting for a unblock everywhere
- And a answer why you deleted my comments and what I wrote in them because I can't see what I wrote in the deleted comments. So I don't know what I wrote that made you mad again and triggered you lol

**Comment by NULLYUKI** [comment]
@PrincessAkira 

Comment deletion is against my freedom of free speech!

**Comment by HerXayah** [comment]
Stop the offtopic.

**Comment by NULLYUKI** [comment]
> Stop the offtopic.

Just unblock me everywhere lol also this was not off-topic and was a violation against the freedom of speech!



> @PrincessAkira If you could unblock me on Discord, we would have a **MUCH** better communication when we need to discuss things about the project.

**Comment by NULLYUKI** [comment]
Deleting comments is pretty unnecessary lool 
grafik

**Comment by NULLYUKI** [comment]
# It has been now 3 weeks lol

**Comment by NULLYUKI** [comment]
# It has been 3 weeks now

**Comment by NULLYUKI** [comment]
Also deleting comments is useless lol

**Comment by NULLYUKI** [comment]
@PrincessAkira Just unblock me everywhere lol xd

**Pull request closed without merging**
